### ISSUE TITLE
[Feature Suggestion] Drag and drop to move page to another position

### ISSUE THREAD

**Issue by BanCrash** [napsternxg/ReadLater#27]
Hello, I am using this extension long time ago and it is very useful. However I think could be cool if you can drag and drop a page to change its position.

For example, drag the last page and drop it on the first place, then the previous first page will be the second, etc. This would be great to manually order the pages, to have the more importants in the first places.

Thanks for the awesome extension in any case!

**Comment by napsternxg** [comment]
Hi @BanCrash , I am glad that you find the extension useful and thanks for the feature suggestion. 

Because of my other commitments, I don't add features to this extension very often. 
Furthermore, the core motivation behind building this extension was to keep it very simple. 

Based on the current design of the extension as, adding any interactive functionality over the presentation of links would be a bit cumbersome. 

If you want, you can send me a pull request with the feature enhancement, and I will try to include your changes.
